# Generated by Django 6.0 on 2026-02-11 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('gst_certificate', models.FileField(upload_to='agency_gst_certificates/')),
                ('company_phone', models.CharField(max_length=15, unique=True)),
                ('company_address', models.TextField()),
                ('company_district', models.CharField(max_length=100)),
                ('company_state', models.CharField(max_length=100)),
                ('company_pincode', models.CharField(max_length=6)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('owner_age', models.PositiveIntegerField()),
                ('owner_dob', models.DateField()),
                ('owner_address', models.TextField()),
                ('owner_district', models.CharField(max_length=100)),
                ('owner_state', models.CharField(max_length=100)),
                ('owner_pincode', models.CharField(max_length=6)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engineerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.CharField(choices=[('BE', 'BE'), ('ME', 'ME'), ('MTech', 'BTech'), ('MTech', 'MTech'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Others', 'Others')], max_length=20)),
                ('other_degree', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('clg_district', models.CharField(max_length=100)),
                ('degree_certificate', models.FileField(upload_to='engineer_certificates/')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel'), ('bricks', 'Bricks'), ('sand', 'sand'), ('others', 'Others')], max_length=20)),
                ('other_product_type', models.CharField(blank=True, help_text='Required if product type is Others', max_length=100, null=True)),
                ('brand_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Construct.agencyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spc_product_name', models.CharField(max_length=200)),
                ('size_or_weight', models.CharField(help_text='Ex: 50kg, 25kg, 8mm, 12mm', max_length=50)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('piece', 'Piece')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(help_text='Available stock count')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Construct.product')),
            ],
        ),
    ]
