# Generated by Django 6.0 on 2026-02-12 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('house', 'House'), ('building', 'Building'), ('flats', 'Flats'), ('commercial', 'Commercial Stores'), ('others', 'Others')], max_length=20)),
                ('total_sqft', models.FloatField()),
                ('site_map', models.FileField(blank=True, null=True, upload_to='site_maps/')),
                ('blueprint_file', models.FileField(blank=True, null=True, upload_to='site_blueprints/')),
                ('building_area_sqft', models.FloatField()),
                ('approximate_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Planning', max_length=20)),
                ('site_address', models.TextField()),
                ('site_district', models.CharField(max_length=100)),
                ('site_state', models.CharField(max_length=100)),
                ('site_pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_address', models.TextField()),
                ('owner_district', models.CharField(max_length=100)),
                ('owner_pincode', models.CharField(max_length=10)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Construct.constructionsite')),
            ],
        ),
    ]
