# Generated by Django 6.0 on 2026-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0002_constructionsite_siteowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
