# Generated by Django 6.0 on 2026-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0003_constructionsite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
