# Generated by Django 6.0 on 2026-02-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0004_constructionsite_other_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsite',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('NearComplete', 'Near To Complete'), ('Completed', 'Completed'), ('HandedOver', 'Handed Over')], default='Planning', max_length=20),
        ),
    ]
