# Generated by Django 6.0 on 2026-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0005_alter_constructionsite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.TextField(default='TIRUPUR'),
        ),
    ]
