# Generated by Django 6.0 on 2026-02-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0006_product_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('weight_or_size', models.CharField(max_length=100)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construct.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Construct.constructionsite')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Construct.productvariants')),
            ],
        ),
    ]
