# Generated by Django 6.0 on 2026-02-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0008_quotationrequest_quotationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Checked', 'Checked'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20),
        ),
        migrations.CreateModel(
            name='EstimatedQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_estimate', to='Construct.quotationrequest')),
            ],
        ),
    ]
