# Generated by Django 6.0 on 2026-02-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0009_alter_quotationrequest_status_estimatedquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedquotation',
            name='base_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20),
        ),
    ]
