# Generated by Django 6.0 on 2026-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0010_estimatedquotation_base_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedquotation',
            name='base_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
