# Generated by Django 6.0 on 2026-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0012_order_orderdelivery_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('AgencyApproved', 'Agency Approved'), ('AgencyRejected', 'Agency Rejected'), ('Processing', 'Processing'), ('OutForDelivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=30),
        ),
    ]
