# Generated by Django 6.0 on 2026-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('MOVED_For_Order', 'Converted To Order')], default='Requested', max_length=20),
        ),
    ]
