# Generated by Django 6.0 on 2026-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0014_alter_quotationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
