# Generated by Django 6.0 on 2026-02-17 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0015_orderdelivery_dispatched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('weight_or_size', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_items', to='Construct.estimatedquotation')),
            ],
        ),
    ]
