# Generated by Django 6.0 on 2026-03-09 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0016_finalquotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='delivery_preference',
            field=models.CharField(choices=[('urgent', 'Urgent (1-2 days)'), ('3days', 'Within 3 days'), ('7days', 'Within 1 week'), ('flexible', 'Flexible')], default='flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationrequest',
            name='expected_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
