# Generated by Django 6.0 on 2026-03-10 07:12

import Construct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0017_quotationrequest_delivery_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='quotation_valid_until',
            field=models.DateTimeField(default=Construct.models.QuotationRequest.default_valid_until),
        ),
    ]
