# Generated by Django 6.0 on 2026-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0018_quotationrequest_quotation_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('MOVED_For_Order', 'Converted To Order')], default='Requested', max_length=20),
        ),
    ]
