# Generated by Django 6.0 on 2026-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construct', '0019_alter_quotationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
